#! /bin/sh
# @(#) $Tau: core/buildtools/ci/before_install $

## ------------------------------------------------------------------------- ##
##                          T A U    P R O J E C T                           ##
## ------------------------------------------------------------------------- ##
##                                                                           ##
##  Licensed under the Apache License, Version 2.0 (the "License");          ##
##  you may not use this file except in compliance with the License.         ##
##                                                                           ##
##  You may obtain a copy of the License at:                                 ##
##                                                                           ##
##      http://www.apache.org/licenses/LICENSE-2.0                           ##
##                                                                           ##
##  Unless required by applicable law or agreed to in writing, software      ##
##  distributed under the License is distributed on an "AS-IS" BASIS,        ##
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. ##
##  See the License for the specific language governing permissions and      ##
##  limitations under the License.                                           ##
##                                                                           ##
## ------------------------------------------------------------------------- ##

set -e

echo "Installing packages" >&2

sudo apt-get update -qq -y
sudo apt-get install -qq -y docker-ce automake autoconf make

if ! test x"${DOCKER_USERNAME}" = x"" ; then
	echo "Logging into Docker Hub" >&2
	echo ${DOCKER_PASSWORD} | docker login --username="${DOCKER_USERNAME}" --password-stdin
fi

if ! test x"$ENCRYPTION_LABEL" = x"" && test -r buildtools/keyring.tar.enc ; then
	echo "Decrypting keyring" >&2
	ENCRYPTED_KEY_VAR="encrypted_${ENCRYPTION_LABEL}_key"
	ENCRYPTED_IV_VAR="encrypted_${ENCRYPTION_LABEL}_iv"
	ENCRYPTED_KEY=$(eval echo \$${ENCRYPTED_KEY_VAR})
	ENCRYPTED_IV=$(eval echo \$${ENCRYPTED_IV_VAR})
	openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV -in buildtools/keyring.tar.enc -out buildtools/keyring.tar -d
	chmod 600 buildtools/keyring.tar
	( cd buildtools && tar xf keyring.tar )
	rm buildtools/keyring.tar
fi

if test -d buildtools/keyring/docker ; then
	mkdir -p $HOME/.docker/trust/private
	cp buildtools/keyring/docker/*.key $HOME/.docker/trust/private
fi
